### ISSUE TITLE
kubectl ssh doesnt show command prompt

### ISSUE THREAD

**Issue by yasir2000** [jordanwilson230/kubectl-plugins#29]
Either of below doesnt work well with me:
```
- kubectl ssh -d -u root -n kong -c kong kong-5c6d75696c-dj95q -- /bin/bash
- kubectl exec --user root kong-5c6d75696c-dj95q -c kong -- /bin/bash
```
I need to install a lua Kong plugin as root only:
` luarocks install lua-resty-openidc`

Am getting no command prompt, just blanks even after pressing enter's

**Comment by jordanwilson230** [comment]
Hey @yasir2000.  I'm not at my computer at the moment to take a closer look, but while you are running the command, can you open another terminal, run the kubectl get pod command (in that same namespace), and tell me what the output is from there?  If you see a pod in an error state, do a describe on it as well and see what it says.  If you see no pod being launched (while executing this plugin), try a kubectl get event command in the namespace and see what the output says. Let me know if that helped!

**Comment by yasir2000** [comment]
> Hey @yasir2000. I'm not at my computer at the moment to take a closer look, but while you are running the command, can you open another terminal, run the kubectl get pod command (in that same namespace), and tell me what the output is from there? If you see a pod in an error state, do a describe on it as well and see what it says. If you see no pod being launched (while executing this plugin), try a kubectl get event command in the namespace and see what the output says. Let me know if that helped!

when i run 
`kubectl get pod`
i get

```
NAME                                      READY   STATUS    RESTARTS   AGE
chart-1606465804-konga-57dcdbb795-m52bm   1/1     Running   0          4d12h
echo-78b867555-6q9dx                      1/1     Running   0          6d14h
ingress-kong-5f558c6f9f-x695r             2/2     Running   0          6d2h
kong-5c6d75696c-dj95q                     2/2     Running   0          7d8h
kong-5c6d75696c-qrw2s                     2/2     Running   0          7d8h
kong-admin-ui-v1-77757b68f6-hr8qt         1/1     Running   0          7d6h
kong-postgresql-0                         1/1     Running   0          7d8h
values.yaml-konga-6d5bbb9ccc-j8r9h        1/1     Running   0          4d12h
```




when i run 
`kubectl ssh -d -u root -n kong -c kong kong-5c6d75696c-dj95q -- /bin/bash
` 

I get:


```
+ getopts hdp:n:u:c: arg
+ case $arg in
+ USERNAME=root
+ getopts hdp:n:u:c: arg
+ case $arg in
+ NAMESPACE=kong
+ KUBECTL+=' --namespace=kong'
+ getopts hdp:n:u:c: arg
+ case $arg in
+ CONTAINER=kong
+ getopts hdp:n:u:c: arg
+ shift 7
+ [[ -z x ]]
+ POD=kong-5c6d75696c-dj95q
+ shift
+ [[ 2 -gt 0 ]]
+ [[ -- == \-\- ]]
+ shift
+ COMMAND=/bin/bash
+ echo -e '\nConnecting...\nPod: kong-5c6d75696c-dj95q\nNamespace: kong\nUser: root\nContainer: kong\nCommand: /bin/bash\n'

Connecting...
Pod: kong-5c6d75696c-dj95q
Namespace: kong
User: root
Container: kong
Command: /bin/bash

+ temp_container=ssh-pod-30476
++ /usr/local/bin/kubectl --namespace=kong get pod kong-5c6d75696c-dj95q -o 'go-template={{.spec.nodeName}}'
+ NODENAME=st000kks04
+ NODESELECTOR='"nodeSelector": {"kubernetes.io/hostname": "st000kks04"},'
++ /usr/local/bin/kubectl --namespace=kong get pod kong-5c6d75696c-dj95q '-ojsonpath={.spec.tolerations[].value}'
+ TOLERATION_VALUE=
+ [[ -n '' ]]
+ TOLERATIONS=
+ [[ kong != \N\O\N\E ]]
++ eval '/usr/local/bin/kubectl --namespace=kong' get pod kong-5c6d75696c-dj95q -o 'go-template='\''{{ range .status.containerStatuses }}{{ if eq .name "kong" }}{{ .containerID }}{{ end }}{{ end }}'\'''
+++ /usr/local/bin/kubectl --namespace=kong get pod kong-5c6d75696c-dj95q -o 'go-template={{ range .status.containerStatuses }}{{ if eq .name "kong" }}{{ .containerID }}{{ end }}{{ end }}'
+ DOCKER_CONTAINERID=docker://f009ab6c536133253ca7cf048e9e51e740d4d76e37394126266ecb45c3ec1913
+ CONTAINERID=f009ab6c536133253ca7cf048e9e51e740d4d76e37394126266ecb45c3ec1913
+ read -r -d '' OVERRIDES
++ to_json /bin/bash
++ text=/bin/bash
++ p=
++ for i in '$text'
++ [[ -n '' ]]
++ p+='"/bin/bash"'
++ echo -en '"/bin/bash"'
+ :
+ trap '$KUBECTL delete pod $temp_container >/dev/null 2>&1 &' 0 1 2 3 15
+ eval '/usr/local/bin/kubectl --namespace=kong' run -it --restart=Never --image=docker '--overrides='\''{
    "apiVersion": "v1",
    "spec": {
        "containers": [
            {
                "image": "docker",
                "name": "'\''ssh-pod-30476'\''",
                "stdin": true,
                "stdinOnce": true,
                "tty": true,
                "restartPolicy": "Never",
                "args": [
                  "exec",
                  "--privileged",
                  "-it",
                  "-u",
                  "root",
                  "f009ab6c536133253ca7cf048e9e51e740d4d76e37394126266ecb45c3ec1913",
                  "/bin/bash"
                ],
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/docker.sock",
                        "name": "docker"
                    }
                ]
            }
        ],

        "nodeSelector": {"kubernetes.io/hostname": "st000kks04"},



        "volumes": [
            {
                "name": "docker",
                "hostPath": {
                    "path": "/var/run/docker.sock",
                    "type": "File"
                }
            }
        ]
    }
}'\''' ssh-pod-30476
++ /usr/local/bin/kubectl --namespace=kong run -it --restart=Never --image=docker '--overrides={
    "apiVersion": "v1",
    "spec": {
        "containers": [
            {
                "image": "docker",
                "name": "ssh-pod-30476",
                "stdin": true,
                "stdinOnce": true,
                "tty": true,
                "restartPolicy": "Never",
                "args": [
                  "exec",
                  "--privileged",
                  "-it",
                  "-u",
                  "root",
                  "f009ab6c536133253ca7cf048e9e51e740d4d76e37394126266ecb45c3ec1913",
                  "/bin/bash"
                ],
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/docker.sock",
                        "name": "docker"
                    }
                ]
            }
        ],

        "nodeSelector": {"kubernetes.io/hostname": "st000kks04"},



        "volumes": [
            {
                "name": "docker",
                "hostPath": {
                    "path": "/var/run/docker.sock",
                    "type": "File"
                }
            }
        ]
    }
}' ssh-pod-30476
```


and when i run  

`kubectl exec --user root kong-5c6d75696c-dj95q -c kong -- /bin/bash
`I get 

`error: auth info "root" does not exist
`

**Comment by jordanwilson230** [comment]
What's the output of kubectl get event?  When the plugin runs, it creates a temporary container named something like "ssh-pod-xxx".  If that pod isn't appearing when you run kubectl get pod, then something is preventing it from running...and kubectl get event should provide a description of what's wrong.

**Comment by yasir2000** [comment]
```
<unknown>   Warning   FailedScheduling   pod/ssh-pod-25226   0/6 nodes are available: 2 Insufficient cpu, 4 node(s) didn't match node selector.
<unknown>   Warning   FailedScheduling   pod/ssh-pod-25226   0/6 nodes are available: 2 Insufficient cpu, 4 node(s) didn't match node selector.

```

Although I increased namespace limits to no limits , here is yaml:

```
kind: Pod
apiVersion: v1
metadata:
  name: ssh-pod-9391
  namespace: kong
  labels:
    run: ssh-pod-9391
  annotations:
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, memory request for container ssh-pod-9391;
      cpu, memory limit for container ssh-pod-9391
spec:
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
        type: File
    - name: default-token-682k5
      secret:
        secretName: default-token-682k5
        defaultMode: 420
  containers:
    - name: ssh-pod-9391
      image: docker
      args:
        - exec
        - '--privileged'
        - '-it'
        - '-u'
        - root
        - f009ab6c536133253ca7cf048e9e51e740d4d76e37394126266ecb45c3ec1913
        - /bin/bash
      resources:
        limits:
          cpu: 1700m
          memory: 2100Mi
        requests:
          cpu: 510m
          memory: 490Mi
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
        - name: default-token-682k5
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      stdin: true
      stdinOnce: true
      tty: true
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  nodeSelector:
    kubernetes.io/hostname: st000kks04
  serviceAccountName: default
  serviceAccount: default
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
```
